# Generated by Django 5.1 on 2025-02-11 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sender_number', models.CharField(max_length=20)),
                ('receiver_number', models.CharField(max_length=20)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_wa_number', models.CharField(max_length=15, unique=True)),
                ('company_address', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Company_Logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('template_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('status', models.CharField(default='Sent', max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('button_clicked', models.CharField(blank=True, max_length=255, null=True)),
                ('button_clicked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('sa_full_name', models.CharField(max_length=25)),
                ('sa_email', models.EmailField(max_length=254)),
                ('sa_username', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('sa_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('template_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('user_role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], default='Admin', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsApp_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, unique=True)),
                ('group_description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='whatsapp.whatsapp_group')),
            ],
            options={
                'unique_together': {('group', 'number', 'email')},
            },
        ),
    ]
