# Generated by Django 5.1 on 2025-02-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelog',
            name='response_received',
        ),
        migrations.AddField(
            model_name='messagelog',
            name='button_clicked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='button_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(default='Sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
